// generated by stringer -type=Activity; DO NOT EDIT

package gopher

import "fmt"

const _Activity_name = "WaitingWonderingBoringLoving"

var _Activity_index = [...]uint8{0, 7, 16, 22, 28}

func (i Activity) String() string {
	if i+1 >= Activity(len(_Activity_index)) {
		return fmt.Sprintf("Activity(%d)", i)
	}
	return _Activity_name[_Activity_index[i]:_Activity_index[i+1]]
}
